import { supabase } from "../utils/supabase/client";

export async function listPublicSections() {
  const { data, error } = await supabase
    .from("MenuSection")
    .select("*")
    .order("Name", { ascending: true });

  if (error) throw error;
  return data;
}

export async function listAllSectionsAdmin() {
  const { data, error } = await supabase
    .from("MenuSection")
    .select("*")
    .order("Name", { ascending: true });

  if (error) throw error;
  return data;
}

export async function createSection(section) {
  // section should include: Name, Description, Availability
  // id is auto-generated by DB
  const { data, error } = await supabase
    .from("MenuSection")
    .insert([section])
    .select()
    .single();

  if (error) throw error;
  return data;
}

export async function updateSection(id, patch) {
  const { data, error } = await supabase
    .from("MenuSection")
    .update(patch)
    .eq("id", id)
    .select()
    .single();
  if (error) throw error;
  return data;
}

export async function deleteSection(id) {
  const { error } = await supabase.from("MenuSection").delete().eq("id", id);
  if (error) throw error;
  return true;
}