"use client";

import { useState } from "react";
import * as menuService from "@/backend/services/menu.service";

export default function MenuTestPage() {
  const [log, setLog] = useState([]);
  const [busy, setBusy] = useState(false);
  const [adminMenu, setAdminMenu] = useState(null);

  function push(msg) {
    setLog((prev) => [...prev, `[${new Date().toLocaleTimeString()}] ${msg}`]);
  }

  async function runTest() {
    setBusy(true);
    setLog([]);
    setAdminMenu(null);

    let sectionId = null;
    let itemAId = null;
    let itemBId = null;

    try {
      push("Creating section (UUID PK auto-generated by Supabase)...");
      const section = await menuService.createSection({
        Name: "TEST SECTION",
        Description: "Temporary section for testing",
        Availability: true,
      });
      sectionId = section.id;
      push(`✅ Section created. id=${sectionId}`);

      push("Creating item A...");
      const itemA = await menuService.createItem({
        Name: "TEST ITEM A",
        Price: 99.0,
        Availability: true,
        Description: "Temporary item A",
        ImagePath: "no-image/No-Image-Placeholder.png",
      });
      itemAId = itemA.id;
      push(`✅ Item A created. id=${itemAId}`);

      push("Creating item B...");
      const itemB = await menuService.createItem({
        Name: "TEST ITEM B",
        Price: 149.0,
        Availability: true,
        Description: "Temporary item B",
        ImagePath: "no-image/No-Image-Placeholder.png",
      });
      itemBId = itemB.id;
      push(`✅ Item B created. id=${itemBId}`);

      push("Linking items to section (MenuSectionItem) with sort_order...");
      await menuService.addItemToSection({
        menu_section_id: sectionId,
        menu_item_id: itemAId,
        sort_order: 20,
      });
      push("✅ Linked item A to section @ sort_order=20");

      await menuService.addItemToSection({
        menu_section_id: sectionId,
        menu_item_id: itemBId,
        sort_order: 10,
      });
      push("✅ Linked item B to section @ sort_order=10");

      push("Updating item A global price to 123...");
      await menuService.updateItem(itemAId, { Price: 123.0 });
      push("✅ Item A price updated.");

      push("Swapping order: make item A appear before item B...");
      await menuService.updateLink(sectionId, itemAId, { sort_order: 5 });
      push("✅ Updated link sort_order for item A to 5");

      push("Fetching admin menu (should show TEST SECTION with items sorted)...");
      const menu = await menuService.getAdminMenu();
      setAdminMenu(menu);

      // ✅ FIX: getAdminMenu() returns { sections, unassignedItems }
      const found = (menu?.sections || []).find((x) => x?.section?.id === sectionId);

      if (!found) {
        push("⚠️ Could not find TEST SECTION in getAdminMenu() response.");
      } else {
        // ✅ Visual: show sort_order + name
        const visual = (found.items || [])
          .map((it) => `${it.sort_order ?? "?"}:${it.Name}`)
          .join(" | ");

        const names = (found.items || []).map((it) => it.Name).join(", ");

        push(`✅ Found TEST SECTION. Items order: ${names}`);
        push(`🧭 Visual (sort_order:name): ${visual}`);
      }

      // Optional: verify unassigned list exists
      const unassignedCount = menu?.unassignedItems?.length ?? 0;
      push(`📦 Unassigned items count: ${unassignedCount}`);

      push("✅ Test complete.");
    } catch (e) {
      push(`❌ Error: ${e?.message || JSON.stringify(e)}`);
      push(
        "If this is RLS: confirm INSERT/UPDATE policies allow admin on MenuSection, MenuItem, and MenuSectionItem via WITH CHECK (public.is_admin())."
      );
    } finally {
      setBusy(false);
    }
  }

  async function cleanup() {
    setBusy(true);
    try {
      push("Cleaning up test data...");

      const items = await menuService.listAllItemsAdmin();
      const testItems = (items || []).filter((x) =>
        ["TEST ITEM A", "TEST ITEM B"].includes(x.Name)
      );

      const secs = await menuService.listAllSectionsAdmin();
      const testSecs = (secs || []).filter((x) => x.Name === "TEST SECTION");

      // Remove links for our test items + sections
      for (const s of testSecs) {
        for (const it of testItems) {
          try {
            push(`Removing link section=${s.id} item=${it.id}`);
            await menuService.removeItemFromSection({
              menu_section_id: s.id,
              menu_item_id: it.id,
            });
          } catch (_) {
            // ignore if link doesn't exist
          }
        }
      }

      // Delete items
      for (const it of testItems) {
        push(`Deleting item ${it.id}`);
        await menuService.deleteItem(it.id);
      }

      // Delete sections
      for (const s of testSecs) {
        push(`Deleting section ${s.id}`);
        await menuService.deleteSection(s.id);
      }

      push("✅ Cleanup done.");
    } catch (e) {
      push(`❌ Cleanup error: ${e?.message || JSON.stringify(e)}`);
    } finally {
      setBusy(false);
    }
  }

  return (
    <main style={{ maxWidth: 1000, margin: "0 auto", padding: 24 }}>
      <h1>Admin Menu Test Panel</h1>
      <p>This validates RLS + CRUD + many-to-many linking + sort_order + menu grouping.</p>

      <div style={{ display: "flex", gap: 10, marginTop: 12 }}>
        <button disabled={busy} onClick={runTest} style={{ padding: "10px 14px" }}>
          {busy ? "Running..." : "Run Menu CRUD + Link Test"}
        </button>
        <button disabled={busy} onClick={cleanup} style={{ padding: "10px 14px" }}>
          Cleanup Test Data
        </button>
      </div>

      <section style={{ marginTop: 18 }}>
        <h3>Logs</h3>
        <pre
          style={{
            background: "#111",
            color: "#0f0",
            padding: 12,
            borderRadius: 10,
            overflow: "auto",
            minHeight: 180,
          }}
        >
          {log.join("\n")}
        </pre>
      </section>

      {adminMenu && (
        <section style={{ marginTop: 18 }}>
          <h3>Admin Menu Snapshot</h3>
          <pre style={{ background: "#f6f6f6", padding: 12, borderRadius: 10, overflow: "auto" }}>
            {JSON.stringify(adminMenu, null, 2)}
          </pre>
        </section>
      )}
    </main>
  );
}